### ISSUE TITLE
As a user I would like Default values for currencies, country/region, trip type, and vehicle / transportation type

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#104]
Default values can be fetched from [/DefaultSet](https://equinor.github.io/hr-api-docs/travelexpense/#operation/getDefaultSet)

**Requirements**
- [x] Should display a default country/region when adding destinations
- [x] Should display a default currency when adding expense
- [x] Should display a default trip type when adding destination
- [x] Should display a default transportation type when adding mileage

**Comment by ntorsen** [comment]
Default values are set for different fields ✅
Country/region: Norway
Currency: Norwegian Krone
Trip type: Business trip
Transportation type: Ordinary mileage
