### ISSUE TITLE
It should be possible to delete travels/expense recordings with status approved

### ISSUE THREAD

**Issue by mglendrange** [equinor/mad-expense-and-pay-app#108]
In the existing app and in SAP PR05 it is possible to delete travels/expense recordings with status set to approved. This options needs to be available in the new app as well.

**Requirements**
- [x] Should let the user delete approved travels
- [x] Should let the user delete approved expense recordings
- [x] To make sure the user doesn't accidentally delete an item, an 'Are you sure?' message should be displayed before continuing

**Comment by tormodAase** [comment]
Added some requirements. I decided there should be a warning message before the user can delete an item

**Comment by tormodAase** [comment]
Merged #110 into this issue

**Comment by tormodAase** [comment]
@ntorsen 32387 is building now, should be ready for test in around 1 hour

**Comment by tormodAase** [comment]
32450 ready

**Comment by ntorsen** [comment]
This has been tested with build 32450, and all requirements pass ✔
- Able to delete approved travel expenses
- Able to delete approved expense recordings
- Warning message appear before deleting item
- Travel expense and expense recording is removed from list in SAP (PR05 and ZR05)

@tormodAase
