### ISSUE TITLE
It should be possible to edit travels/expense recordings with status approved

### ISSUE THREAD

**Issue by mglendrange** [equinor/mad-expense-and-pay-app#111]
In the existing app and in SAP PR05 it is possible to edit travels and expense recordings with status set to approved. This options needs to be available in the new app as well.

**Requirements**
- [x] The user should be able to edit an approved travel
- [x] The user should be able to edit an approved expense recording
- [x] If the user makes any changes, the status should go back to being a draft, and the confirm and send button should be available again
- [x] For approved items, the default tab should be summary page
- [x] When going back to the main page from New Travel Expense / Edit Travel Expense / New Expense Recording / Edit Expense Recording, or when clicking "Confirm and send", it should reload the list of travels/expense recordings. This is an unrelated quality of life fix that should be there anyway, but I added it as a requirement to this issue to fix some edge cases

**Comment by tormodAase** [comment]
What happens if a user edits an approved travel expense / expense recording? Will it go back to being a draft? Does the user have to confirm and send again?

**Comment by mglendrange** [comment]
@tormodAase yes, it goes back to being in status draft and should be treated as any other travel in status draft, meaning that you have to confirm and send again.

**Comment by tormodAase** [comment]
I added some requirements and merged the cards and will close #109

**Comment by tormodAase** [comment]
@ntorsen 32387 is building now, should be ready for test in around 1 hour

**Comment by ntorsen** [comment]
@tormodAase something is wrong with Expense&Pay-Test (32387) build, it crashes. Seems like I have been removed as tester from where I usually have been doing my testing. in Expense&Pay-Q97
![image](https://user-images.githubusercontent.com/89014017/171848410-decab687-8eee-4d8d-b497-bcfb8719b3d1.png)

**Comment by tormodAase** [comment]
32450 ready

**Comment by ntorsen** [comment]
Tested on build 32450, what has been tested and is working ✅
- Able to edit an approved travel expense
- Able to edit an approved expense recording
- Making changes, the status go back to being in draft, and confirm and send button is available again
- The default tab is the summary page for approved items
- Going back to the main page from new travel/edit travel expense/new expense recording/edit expense recording, or clicking confirm and send, reload the list of travels/expense recordings

@tormodAase
