### ISSUE TITLE
Add delete button for travel and expense recordings on travel details page

### ISSUE THREAD

**Issue by mglendrange** [equinor/mad-expense-and-pay-app#112]
Inside the existing app there is a kebab menu in the top right corner when viewing a travel/expense recording. One of the options there is to delete the travel/expense recording. I see that Øysteins prototype have the same kebab menu:

![Image](https://user-images.githubusercontent.com/6025616/171124115-0e636cdb-831c-428c-85a4-206ee5baee65.png)

I think it would be nice to add a delete button here from a usability/user experience point of view.

**Comment by dbjoEq** [comment]
@ntorsen 👋
Ready for testing in QA. (Build: 32584).

**Test Rquirments**

- [ ]  Kebab menu top right corner after opening expense.
- [ ]  Option to delete
- [ ]  After delete redirects back to main page. (Sometimes after redirect there is a very short pause before the deleted expense gets removed. Let me know if you think this is not working well enough 😊 )

**Comment by ntorsen** [comment]
@dbjoEq this is working good 💪
