### ISSUE TITLE
Add button for viewing travel slip/expense recording slip inside details page

### ISSUE THREAD

**Issue by mglendrange** [equinor/mad-expense-and-pay-app#113]
Inside the existing app there is a kebab menu in the top right corner when viewing a travel/expense recording. One of the options there is to view a PDF with a summary of the travel/expense recording. I see that Øysteins prototype have the same kebab menu:

![Image](https://user-images.githubusercontent.com/6025616/171124115-0e636cdb-831c-428c-85a4-206ee5baee65.png)

I can do a check off, but I suspect that this is a functionality that will be requested.

**Comment by mglendrange** [comment]
@tormodAase I have added an endpoint for getting the PDF, ref https://equinor.github.io/hr-api-docs/travelexpense/#operation/getTravelSlip

**Comment by dbjoEq** [comment]
@mglendrange 👋 
Do we have some more sketches on how the kebab menu should look open, and what menu options there should be? PDF Summary and maybe a delete slip option, anything else? 😊

**Comment by mglendrange** [comment]
@dbjoEq found out I had taken a screenshot of how it look today

![92C9E7EF-5E2D-4FF9-BD5B-5281D910D8B7](https://user-images.githubusercontent.com/6025616/173016669-b5fe87a5-bad4-4290-9043-60f088a5ceff.png)

**Comment by dbjoEq** [comment]
@mglendrange Thats great, thank you! 😊

**Comment by dbjoEq** [comment]
@ntorsen 👋 
Ready for testing in QA. (Build: 32584).

**Test Rquirments**
- [ ] Kebab menu top right corner after opening expense.
- [ ] Option to view summary as pdf
- [ ] Display pdf
- [ ] Possible to share pdf

**Comment by ntorsen** [comment]
@dbjoEq working good, want to add that I also like that I can zoom in/out when viewing the summary as pfd 🤩

**Comment by ntorsen** [comment]
One thing that is not in the requirements, but is something Magnus mention is possible in the old app - should we be able to create copy from menu?

**Comment by dbjoEq** [comment]
> One thing that is not in the requirements, but is something Magnus mention is possible in the old app - should we be able to create copy from menu? @dbjoEq

@ntorsen 👋 
I talked with Magnus, and create copy is not a feature that has been discussed yet. 😊
