### ISSUE TITLE
Breakfast should be selected if the user's first destination is Norway

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#118]
**Requirements**
- [x] If the user's **first** destination is Norway, we should enable breakfast deduction for all days as long as meals have been untouched

**Comment by ntorsen** [comment]
### Results from testing on build 32464
- If user's destination is Norway, and no meals have been touched, and user leaves it 'in draft' - breakfast deduction is **not** enabled for all days (goes for both SAP and app). And if user goes back to app it will have the private accommodation checked off
- If user's destination is Norway and no meals have been touched, but user confirm&send travel - then breakfast is enabled for all days (both in SAP and app)
**--> We should have the same functionality here for when leaving a travel in draft and confirm&send** 🐛

- If user's destination is Norway and user checks off other meal deductions (lunch and dinner) - breakfast is still set as default even though user has not touched that. Goes for both leaving a travel in draft and confirm&send 
**--> this is good** 👍

- If user destination is abroad (not Norway), no meals has been touched, and in draft - then private accommodation is checked off as default. Same goes for when user creates a new travel and click confirm&send
**--> guessing this is correct functionality (?), seems to be correct as I get the same result for in draft as for confirm&send**👍

- If user selects abroad as first destination, and then Norway as second - then no meal deduction or private accommodation is checked off if nothing is touched
- If user selects Norway as first destination, and then abroad as second - then breakfast deduction is set as default when meal refunds has not been touched
**---> if you go abroad first then we should have private accommodation set as default ? if we do that for when selecting Norway as first destination and setting breakfast has default?**❓

**Other remarks:**
- If you go into meal refund you get the last date of the travel up two times. Does not seem to have an impact which ones you choose, but it would be good to just have one box per date

![image](https://user-images.githubusercontent.com/89014017/172796415-cafbc319-d8d3-4687-949f-df63f9bc7a62.png)

**Comment by tormodAase** [comment]
There shouldn't be any automatic private accommodation as far as I'm aware. Something for @konrad-drygas to look into.

I wasn't able to reproduce the double date bug

**Comment by ntorsen** [comment]
@tormodAase I'm not able to reproduce the double date bug in build 32474 with a new travel expense. Only way to see it now is to find an old travel expense that has meal deduction

**Comment by tormodAase** [comment]
Build 32496 should be ready after lunch, but we are awaiting @konrad-drygas 's fix. Konrad can you move this card to the test column when the issue is fixed (and no changes are necessary on my end)?

**Comment by tormodAase** [comment]
TripSchema is fixed, ready for test in about an hour @ntorsen . Should no longer overwrite meals/accommodation when you initially create a travel

**Comment by ntorsen** [comment]
@tormodAase , I created two travel, one for Norway and one abroad, and both had private accommodation ticket off. These are just in draft, but SAP also verifies that these have PA. This happened in build 32557

**Comment by tormodAase** [comment]
@ntorsen Ready for test (32694)

**Comment by ntorsen** [comment]
**Tested with build 32694 and it is looking good** 🤩
✅ If first destination is Norway, breakfast deduction is enabled for all days when meals have not been touched
✅ If first destination is a different country than Norway, breakfast is not set as default
✅ If first destination is something different than Norway, a user will always have the Kostgodtgjørelse box checked off, but no meal deduction

![image](https://user-images.githubusercontent.com/89014017/175530888-5e184172-84bd-438e-aec6-a44b3db460c5.png)
![image](https://user-images.githubusercontent.com/89014017/175530907-99101c8d-4c71-4693-93ef-01cb0ccbee1c.png)

✅ There is no automatic private accommodation 
✅ Seems to be working fine when adding meals to trip
✅ Show Summary and when simulating travel in SAP displays correct information

**Questions/findings:**
- I can still reproduce the double date bug in the app

![image](https://user-images.githubusercontent.com/89014017/175529997-02a0bc3f-994d-4840-9a81-3a64a505c8a0.png)

- When adding private accommodation to a travel (either Norway or abroad), it does not seem to add more money when simulating the travel expense. Should not this add more refund to a trip?

@tormodAase

**Comment by tormodAase** [comment]
@konrad-drygas Maybe you know if private accommodation should add more money to the travel?

**Comment by tormodAase** [comment]
Konrad will check on monday

**Comment by konrad-drygas** [comment]
@tormodAase @ntorsen 
I think the best to figure out what should be created when we use the new app is to create a travel in the new app and then create another travel (with the same values) in the old app or in PR05. Then it's possible to compare values. We don't need to analyse how the "Private accom." checkbox works in Equinor. If everything is the same, then it's fine. We do everything correctly. Unfortunately, I don't have the new app, so I can't check it.

**Comment by ntorsen** [comment]
@tormodAase @konrad-drygas 
I created the same travel in the old app and in the new app. What I registered: travel period from Monday 13. June at 08:00 to Friday 17th of June at 17:00. Business trip, Norway, Sola. C.BAX.30.006 as cost allocation. Breakfast as default. Reimbursement amount was 2 964,- before and after adding private accommodation. So new app works the same as it does for old app 👍

**Comment by ntorsen** [comment]
@tormodAase Should we can add a new task for the double date bug and set this one to done?

**Comment by tormodAase** [comment]
@ntorsen Yeah let's do that, since it's only a visual bug and not critical.
