### ISSUE TITLE
Last used values

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#129]
[API Docs](https://equinor.github.io/hr-api-docs/travelexpense/#tag/Last-Used-Values)

**Requirements**
- [x] Show last used values when the user types Reason / Expense Recording title
- [x] Show last used cost centers when adding cost objects
- [x] Show last used WBSes when adding cost objects
- [x] Show last used currencies when adding expenses
- [x] Show last used country/location when adding destination
- [x] Show last used mileage location when adding mileage
- [x] Show last used expense types when adding expense
- [x] Show last used expense description (??) when adding expense
- [x] All last used items should be selectable

**Comment by tormodAase** [comment]
@mglendrange expense description is just a flex field. Do we still want last used values for this field?

**Comment by konrad-drygas** [comment]
@tormodAase Yes, some employees often go on similar trips, so they want to use the same description. Also it was a feature in the old app, so we have to have it.
