### ISSUE TITLE
Add possibility to add names of passengers in Mileage

### ISSUE THREAD

**Issue by ntorsen** [equinor/mad-expense-and-pay-app#140]
This is possible to do in the existing app, and is requested that we have in the new app.

Suggestion: is it possible to add a new field under "Number of passengers" if users selects 2 or more passenger. Then a description field will show up where user can write in the names? 
![image](https://user-images.githubusercontent.com/89014017/175268833-210e45c6-913a-419b-9ab9-dac6b0edcad0.png)

**Comment by tormodAase** [comment]
@konrad-drygas @mglendrange Is this supported by the API?

**Comment by konrad-drygas** [comment]
@tormodAase No, it's not. Working on it.

**Comment by tormodAase** [comment]
Moved to preparing so we don't get confused

**Comment by konrad-drygas** [comment]
My part is done. The field is called FlexPassengerNames, and should only be used when FlexNrOfPassengers is greater than zero. All changes are in Q97 now.

@mglendrange - please update what needs to be updated. 

@tormodAase - you can start using it if no changes in Azure are necessary.

**Comment by SegarJJ** [comment]
number of passengers field needs to support a zero then, as it is a required field.  if a zero, then the names field should not be shown or be turn optional. 👍
