### ISSUE TITLE
MSAL authentication

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#35]
Details can be found here:
https://github.com/equinor/mad-react-native-expo-template/issues/24

- [x] https://github.com/equinor/mad-expo-core/issues/15

Description
Standard Equinor multifactor authentication for iOS devices.

Prod users : everyone in equinor whom is an employee
Q87 and Q97 users are given in the security group:  abc
Dev/Test users are given in the security group: abc

**Comment by SegarJJ** [comment]
moving this into TEST, as it is actively used today.

**Comment by ntorsen** [comment]
Tested on E&P Q97 - have to authenticate with MSAL. 💪
