### ISSUE TITLE
Authenticate users

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#41]
**Description**
Standard Equinor multifactor authentication for iOS devices.
Who can authenticate to which versions?

- Prod users : everyone in equinor whom is an employee 
- Q87 and Q97 users are given in the security group:   
- Dev/Test users are given in the security group:

**Comment by tormodAase** [comment]
Awaiting app regs and SAP

**Comment by SegarJJ** [comment]
using known msal configuration from mad-expo-core

**Comment by SegarJJ** [comment]
we can authenticate with MSAL today, this then seems to be ready for TESTING.

**Comment by ntorsen** [comment]
Tested on E&P Q97 - have to authenticate with MSAL 👍
