### ISSUE TITLE
Create app in Azure Active Directory

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#42]
Create app in Azure Active Directory. As of 13th October 2021 when authenticating with the app it's atheticating to "Hearing Test App Test".

Need to create apps for the following environments:
- DEV
- TEST
- QA
- PROD

Register new app here: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps

**Comment by tormodAase** [comment]
Q97 app reg has been created

**Comment by SegarJJ** [comment]
any indication how far along this has gone?

**Comment by SegarJJ** [comment]
@tormodAase I think this issue is likely done, if so lets close it out.

**Comment by tormodAase** [comment]
Q97 has been created, still need Test and Prod

**Comment by StaaleW** [comment]
Created Test and Prod app.reg. Added @tormodAase  as owner. Fill in the necessary Authentication details
