### ISSUE TITLE
Changes new travel expense

### ISSUE THREAD

**Issue by ntorsen** [equinor/mad-expense-and-pay-app#45]
**Feature changes to Refund page:**
- [x] When ticking off checkboxes for refunds (breakfast, lunch, dinner, private accommodation), all days that are within the travel period dates are selected, but if you go to Meal refund or Accommodation refund and remove first checkbox 'All days' and then press Confirm - it looks like you still get refunded for that even though it says 0 days. This can be a little misleading for users. 

![image](https://user-images.githubusercontent.com/89014017/158348181-d30787af-065c-4a02-841c-7e19a3aea754.png)

- [ ]  X and 'Confirm days'-button work the same way. Clicking on X still confirms page choice. Do we need X-button on Meal refund page and Accommodation refund page?

**Cost Allocation:**
- [ ]  Some user may have difficulty in setting the correct percentage for a specific cost allocation. Is it possible to add a section in editing mode where a user can write directly in the percentage?

![image](https://user-images.githubusercontent.com/89014017/158353629-98aed542-e709-45db-8e06-84c8a672e800.png)

**Select date:**
- [x]  Can we make the Confirm button bigger, and also move the bottom page up a little?
 
![image](https://user-images.githubusercontent.com/89014017/158355052-04121312-fc46-4634-81bd-c021a1da2d2b.png)

**Comment by tormodAase** [comment]
@ntorsen I've made the cost allocation issue into a separate issue #51 

The other issues should soon be available to test. I will let you know when they're available

**Comment by tormodAase** [comment]
@ntorsen Fixes are available to test in 31673

**Comment by ntorsen** [comment]
Looks really good @tormodAase  💪
But I see that X and 'Confirm days'-button still work in the same way. Clicking on X confirms page choice.

For example, check box for Breakfast and all days are refunded. Then you go in to the Breakfast meal refund page and only select Monday, Wednesday, Friday and Sunday, and Confirm those. Then it will correctly say 4 days. When going back again and unselect Monday and X-out, it will still say 4 days (which would be correct since this should not confirm page choice). But then it will change to 3 days when you make another change, lets say you add Lunch or Dinner. So X work the same way as Confirm days, it just need another click to get triggered.

**Comment by ntorsen** [comment]
@tormodAase is it possible to make Breakfast, Lunch, DInner and Private accomodation refund pages available when clicking on them first without having to check the box for it first? Some users may want to view which days to add refunds for instead of choosing 'All days" first

**Comment by ntorsen** [comment]
@tormodAase I think we can move this card to pending release, as we have a different card/issue on GH for the slider on the cost object?
