### ISSUE TITLE
The user should be able to use the cost objects API

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#57]
When a user creates or edits a cost object, the user should be able to:
- [x] Search and select cost center
- [x] Search and select WBS
- [x] The user can't add both a WBS and a Cost center to a cost object. They have to pick one
- [x] Cost allocations can have multiple cost objects, for example 2 WBSes and 3 cost centers
- [x] When looking at cost allocation (in travel details and summary tab), it should display both the id AND the name/description of the cost center / wbs, like below
![image](https://user-images.githubusercontent.com/22524448/164699953-cd9ccef1-4221-48a2-a0c3-e0f16a9ff17d.png)
![image](https://user-images.githubusercontent.com/22524448/164700011-d0d24c52-e47c-4571-a689-cf5db3a3d655.png)

**Comment by tormodAase** [comment]
We will use the cost center API for this https://equinor.github.io/hr-api-docs/costobjects/

**Comment by tormodAase** [comment]
I have a working solution for this now. Created a draft pull request (not ready for review) as I don't want any new pull requests/testing until the huge pull request is fully out of the way

**Comment by tormodAase** [comment]
@ntorsen Ready for test! 32164 should be available in testflight soon!

**Comment by ntorsen** [comment]
### Result from testing on build 32164, Q97
When user creates or edits a cost object, the user should be able to:
✅Search and select cost center
✅Search and select WBS
🐛The user can't add both a WBS and a cost center to a cost object. They have to pick one
✅Cost allocations can have multiple cost objects
✅When looking at cost allocation (in travel details and summary tab), it should display both the ID and the name/description of the cost center/WBS

**Further explanation of what is working good:**
 * When choosing an invalid/blocked cost center/WBS, the icon on the right hand side gives an error description of the problem (example: cost center xxx blocked against direct postings on -date-)
 * Finding a cost center/WBS that is not invalid/blocked, the travel expense sends a draft that is successfully synced to SAP
 * Correct cost center/WBS is displayed in SAP, and with correct percentage
 
![image](https://user-images.githubusercontent.com/89014017/169272626-75c70ddc-cdac-415e-9930-b0bad2a5a1d2.png)


**Remarks:**
* You can add both cost center and WBS to cost object/travel. Here I selected WBS C.XP1.MN.10000 (EXP Management common costs) and cost center CHYTT (Common items CC1000)

![image](https://user-images.githubusercontent.com/89014017/169270439-f509a493-89a3-415e-8ea6-48c9e55e1977.png)

* It's a little difficult to set the exact cost allocation percentage on a cost center/WBS as you cannot type in the number but have to set it on the "line"

![image](https://user-images.githubusercontent.com/89014017/169271583-dc6671c1-8596-4b71-ac3e-9bb610ea8bc0.png)

* Should it say "Search cost center" for both fields?

![image](https://user-images.githubusercontent.com/89014017/169271748-0819d621-4b6d-4551-a866-595c4d20a42b.png)

@tormodAase

**Comment by tormodAase** [comment]
@ntorsen 

> It's a little difficult to set the exact cost allocation percentage on a cost center/WBS as you cannot type in the number but have to set it on the "line"

There's a separate issue for this here https://github.com/equinor/mad-expense-and-pay-app/issues/51

> Should it say "Search cost center" for both fields?

Will update the bottom search to say "Search WBS"

> You can add both cost center and WBS to cost object/travel. Here I selected WBS C.XP1.MN.10000 (EXP Management common costs) and cost center CHYTT (Common items CC1000)

Cost allocation/distribution can have multiple WBSes and Cost centers, but each item/row in SAP can't contain both a WBS and a Cost Center, as far as I'm aware. So the user shouldn't be able to select both a WBS and a Cost Center and click confirm in the "New cost object" screen.
