### ISSUE TITLE
Description/Comment for expenses is not sent to SAP. Awaiting a SAP fix

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#68]
We cannot create a new expense with a comment currently. In the app we therefore send an empty string as comment every time. When the issue is resolved in sap, we can attach a comment to expenses

**Comment by konrad-drygas** [comment]
It is working now for travels and expenses. However, it's necessary to use a flexible field for comments. Changes will be in Q97 soon.
