### ISSUE TITLE
Triptype will not show up on destinations. This is because we don’t get triptype from SAP, only triptype id. Have to discuss with Konrad whether we should get triptype from travel details, or if we have to fetch it separately with the included triptype id.

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#71]
Have to discuss with Konrad whether we should get triptype from travel details, or if we have to fetch it separately with the included triptype id.

**Comment by konrad-drygas** [comment]
@tormodAase I've analysed it and fixed it. Now you will get IDs and descriptions for trip types. It's already in Q97.
