### ISSUE TITLE
Destination field fix

### ISSUE THREAD

**Issue by ntorsen** [equinor/mad-expense-and-pay-app#75]
Found while testing build 31681. 

Destination: User writes in text for country/region and has to click on recommended place in order to add destination. If user writes in the whole word of the country/region, the add destination button is not possible to click. I think the user will be left puzzled if they think they have filled out all fields (trip type, country, location) and add destination-button is not responding.

Adding a screenshot so that you can see more clearly what I mean. Here I found a business trip type in the dropdown and wrote in "France" (without clicking on the suggested countries) and then entered a location. The "Add destination"-button is not possible to click on even if all fields are filled out:
![image](https://user-images.githubusercontent.com/89014017/167823082-e7cbcffc-caf2-4afb-a3a8-bd80b03d73cc.png)

**Comment by tormodAase** [comment]
Should now display a checkmark if you've selected a country. Also applies to country/region in expenses. Build 32496 should be ready after lunch

**Comment by ntorsen** [comment]
Working good @tormodAase  👍
