### ISSUE TITLE
Disable mock response for expense field values

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#83]
Currently we get a mock response when we fetch expense fields.

**Requirements**
- [x] Disable mock-response
- [x] Make sure every possible field has a proper name
- [x] Make sure required fields are filled out before the user can add the expense
- [x] Tell the user which fields are required by marking them with a red asterisk
- [x] Make sure the correct flex fields are available for the user for a given expense type

**Additional requirements for tester**
- [ ] Make sure all the flex field is working as expected. Are the values uploaded to SAP? Are the values retrievable from SAP?
- [ ] as a bonus I've added something called KeyboardAvoidingView to the Expense Modal screen. This should help position the input fields correctly when the keyboard pops up. Would be nice to get feedback on if this is working as expected, and if we should implement it in other screens as well

List of flex fields:

![Image](https://user-images.githubusercontent.com/22524448/171613039-d5867405-89fe-4759-a421-94851c4e16d6.png)

**Comment by tormodAase** [comment]
Soon ready for code review, have some issues with SAP remaining

**Comment by tormodAase** [comment]
These fields are **NOT** in use, and are therefore not expected for testing

**Comment by tormodAase** [comment]
Country/Region is not mandatory according to the data I get from SAP. From my experience now, I'm able to create a new expense without country, but SAP adds a country to the expense. Issue for @konrad-drygas to look into.

I think I've fixed the other issues, build ready after lunch.

**Comment by tormodAase** [comment]
Looks like an automatic build replaced this build. Building a new version now (32531). Should be ready to test in about an hour

**Comment by konrad-drygas** [comment]
> Country/Region is not mandatory according to the data I get from SAP. From my experience now, I'm able to create a new expense without country, but SAP adds a country to the expense. Issue for @konrad-drygas to look into.

@tormodAase It's not a bug, it's a feature. SAP works like that.

**Comment by tormodAase** [comment]
@konrad-drygas Then could we make flexCountryId/flexRegionId mandatory? It's confusing for the end user if Andorra is added to their expense

**Comment by konrad-drygas** [comment]
@tormodAase Everything is fine. It's not Andorra that is added. If you don't fill FlexCountryId, the value from the main Travel entity is used.
