### ISSUE TITLE
Show list of Payslips

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#84]
https://www.figma.com/file/7HZJK17nvKpicBO3SuRWt7/Expense-%26-Pay2?node-id=502%3A38112

API: https://equinor.github.io/hr-api-docs/

**Requirements**
- [x] Display a list of payslips
  - Payslips should display:
  - [x] Title
  - [x] Month/Year
  - [x] Date
  - [x] Amount of money
- [x] Filter by year
- [x] Drag down to refresh
- [ ] Use React Query for currencies and Payslip data

**Comment by tormodAase** [comment]
Some more info for @dbjoEq:

- utils/DateHelper.ts has a function readSapDateAndTime which can be used to read dates from the API (`"/Date(123456789)/" -> DateTime object`)
- Sap does not like encoded spaces. if you plan to send a request with spaces 
(e.g. `/PayslipSet?$filter=SlipKey eq '2022'`), instead send `
/PayslipSet?$filter=SlipKey+eq+'2022'`

**Comment by dbjoEq** [comment]
@ntorsen 
QA version ready for testing. 😊

**Comment by ntorsen** [comment]
Working good on build 32224 Q97 💪
