### ISSUE TITLE
Pressing on a payslip should open the payslip PDF

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#85]
When pressing on a specific payslip in the list, it should open the payslip as pdf. This pdf should be able to download and share with the icon in the top right corner. 

![Image](https://user-images.githubusercontent.com/99209297/169486490-6a884516-a728-4a53-a76e-aef73e7ccee8.png)

**Comment by dbjoEq** [comment]
@ntorsen 👋 
QA version ready to test. 😊
