### ISSUE TITLE
The user should be able to add Mileage

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#86]
[Figma](https://www.figma.com/file/7HZJK17nvKpicBO3SuRWt7/Expense-%26-Pay2?node-id=1049%3A64196)

**Requirements**

- [x] Should be able to add date and time
- [x] Should be able to add start and end location
- [x] Should be able to select vehicle type
- [x] Cost allocation
  - [x] Should be able to select general cost assignment
  - [x] Should also be able to choose another cost allocation
- [x] Flex fields
  - [x] Should be able to add kilometers  
  - [x] Should be able to add amount of passengers
  - [x] Should be able to add weight of baggages
  - [x] Should be able to select country or region

- [x] Should be able to edit mileage
- [x] Should be able to delete mileage 
- [x] Information should be synced to SAP 
- [x] Information should be read from SAP if the user opens a travel from SAP

**Useful information for developer**
- Available vehicle types can be found with `/VehicleTypeSet` endpoint
- Available flex fields can be found with `/FlexibleMileageFieldSet` endpoint

**Important for tester**

- Flex fields might not be available for you. In my case, only kilometers and amount of passengers are available
- I had to make some changes to cost distribution to get it to work with mileage. Cost Distribution for travel should therefore also be tested to make sure it still works as expected

**Comment by ntorsen** [comment]
### Tested on build 32230 Q97
Working really good 🎉I've gone through the requirements, and..
**User is able to:**
- Add date and time
- Add start and end location
- Select vehicle type
- Select general cost assignment
- Choose another cost allocation
- Add kilometer
- Add amount of passengers
-  Edit mileage
- Delete mileage
- Information is synced to SAP
- Information can be read from SAP

![image](https://user-images.githubusercontent.com/89014017/170020489-e140f7b0-fb25-495d-a80d-5e25ef28c2dc.png)

**Remarks:**
- Should a user be able to use comma when filling out kilometers? Now I can just fill out whole numbers. 
- Not able to add weight of baggage
- Not able to select country or region, but there is a field for 'Domestic distance' 
- Not exactly related to mileage, but when I create a new travel expense, it seems like it always select meal refunds for me, even though I have not done anything with it. 

![image](https://user-images.githubusercontent.com/89014017/170022064-bf26f7d2-e3c6-4136-bcdb-8539e4cbe681.png)


@tormodAase

**Comment by ntorsen** [comment]
@tormodAase new build 32241 fixed mileage being cleared from memory when open a new travel expense after previously having opened a travel expense with mileage inside.

**Comment by tormodAase** [comment]
@ntorsen These fields are **NOT** in use:
FlexWeightOfBaggage
FlexCountryId
FlexRegionId

We there don't need to test them, and we can move this card to pending release
