### ISSUE TITLE
New expense - return on description

### ISSUE THREAD

**Issue by ntorsen** [equinor/mad-expense-and-pay-app#87]
If you press return on the keyboard, other apps usually remove keyboard and user is able to view more of the screen. Here you jump further down the description box in order to write more. Expected that return button would finish my writing and I could more easily scroll down the page. 
![image](https://user-images.githubusercontent.com/89014017/167656806-6dad6f9e-c1e1-4999-8b20-b3861e780803.png)

**Comment by tormodAase** [comment]
@ntorsen Is this card still valid? We don't have a Description field anymore (but we do have FlexDescription)

**Comment by ntorsen** [comment]
@tormodAase yes it is still valid. Depending on what ExpenseType you select you can get Description field and/or FlexDescription field, at least for the latest build available (32474)

**Comment by tormodAase** [comment]
Closed because we don't use Description field anymore
