### ISSUE TITLE
Summary displays incorrect information on meal refunds

### ISSUE THREAD

**Issue by ntorsen** [equinor/mad-expense-and-pay-app#89]
Summary displays incorrect information on meal refunds and accommodation. If user adds meal refunds for all days on Breakfast and Dinner, but goes in on Dinner and uncheck all days (by either confirm days or click on X), the summary section will display All x days when that refund isn't checked.

![image](https://user-images.githubusercontent.com/89014017/167820863-511601c5-03d7-4d0a-8489-bd599ebad131.png)

**Comment by tormodAase** [comment]
32531 ready in about an hour

**Comment by ntorsen** [comment]
Working good now 👏
