### ISSUE TITLE
Private Accommocation should just be a toggle. We should no longer select dates

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#96]
There have been some changes to SAP with regards to Private Accommodation / Overnight stay. It no longer acts like a meal, and is instead just a boolean value in SAP. The changes has made it impossible for the user to update travels with meals and accommodation.

**Requirements**
- [x] Accommodation should now only be a checkbox for the user. The user should no longer select dates
- [x] Make sure the user can update meals and accommodation properly in SAP

**Comment by tormodAase** [comment]
@ntorsen This branch should fix issues we have with meals/accommodation. Accommodation is now simply a checkbox. You no longer choose days.

The fix enables us to send meals/accommodation updates to SAP.

I've also updated the summary page to reflect the changes.

Building now, will let you know when it's available

**Comment by tormodAase** [comment]
@ntorsen  32349 Soon available!

**Comment by ntorsen** [comment]
**Result from testing on build 32349**
- Private accommodation works as a boolean, its a checkbox for user to select. User does not select dates
- In SAP, the "Nattillegg" checkbox is ticked if private accommodation is chosen
- User can update meal refunds and private accommodation in SAP, and updated version is available instantly in app/SAP.

**Feedback:**
- if user only selects private accommodation but no meal refund, _usually_ all days are select as default for breakfast
- if user selects other meal refund, like some days with lunch or dinner refund, the breakfast refund is not set as default and does come up as selected in SAP. So it seems like breakfast is only set as default if no other meal refunds has been selected
![image](https://user-images.githubusercontent.com/89014017/171395825-1e0cdc15-cec9-481c-b464-b9cf106592fc.png)

If breakfast is set as default then it should have been checked off even if adding lunch and dinner to the meal refund.. or what do you think about this @tormodAase ?

**Comment by tormodAase** [comment]
Putting this on ice while I figure out with Magnus how we solve the breakfast problem

**Comment by tormodAase** [comment]
@ntorsen I'm merging this branch into main. created a new issue for the breakfast logic

**Comment by tormodAase** [comment]
https://github.com/equinor/mad-expense-and-pay-app/issues/118
