### ISSUE TITLE
Get a list of expense recordings

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad-expense-and-pay-app#99]
As a user I would like to get a list of expense recordings
**Requirements:**
- [x] The screen should be identical to the list of travel expenses, except it should display a list of expense recordings instead of travel expenses
- [x] The placeholder icon can be found here https://www.figma.com/file/7HZJK17nvKpicBO3SuRWt7/Expense-%26-Pay2?node-id=1142%3A65582

**Comment by tormodAase** [comment]
Ready for test (32287)

**Comment by tormodAase** [comment]
@ntorsen

**Comment by ntorsen** [comment]
### Result from testing on build 32287
**What is working good**
* Screen is identical to the list of travel expenses, except it displays list of expense recordings
![image](https://user-images.githubusercontent.com/89014017/170659308-82182730-e116-4ac7-95f3-c701cd18b548.png)

* If there are no expense recordings, user will get a message that there are no registered expense recordings, for that specific year
![image](https://user-images.githubusercontent.com/89014017/170658867-e2397c82-aab7-4438-b503-cab2d3104dcc.png)

Remarks:
* Cannot click on a submitted expense recording to view a summary of it
* Should there be a limit to how far back a user can view their travel expenses/expense recordings? Was able to click back over 30 years
 @tormodAase

**Comment by tormodAase** [comment]
@ntorsen In an ideal world the user should not be able to go back further than their first travel expense / expense recording. However, we request expense recordings / travel expenses year by year, so we don't know which years are empty before the user selects that year.

Will look into the submitted expense recording issue

**Comment by tormodAase** [comment]
@ntorsen summary Fixed in latest build 32297

**Comment by ntorsen** [comment]
Nice work 🤩💪 I can now click on submitted expense recordings and view a summary of it. 

Can we also do something about the title when clicking on a submitted ER @tormodAase ? 
Here is a screenshot of an approved travel expense:

![image](https://user-images.githubusercontent.com/89014017/170700471-cba2015e-4dee-4260-b09c-84ae489bb376.png)

And this is of an approved expense recording:

![image](https://user-images.githubusercontent.com/89014017/170700597-392bdeb3-6e60-4966-b2c4-2b1b5642515e.png)

**Comment by tormodAase** [comment]
@ntorsen 
![Image](https://user-images.githubusercontent.com/22524448/170702041-1ec309e4-aaaf-4fae-a887-d94843618966.png)

Fixed it now. Want me to create a build so you can check?

**Comment by ntorsen** [comment]
@tormodAase sure, if its no hassle for you :) can also wait if you want to add other things to the build as well

**Comment by tormodAase** [comment]
@ntorsen Build 32302 should be ready soon, screen title should be updated

**Comment by ntorsen** [comment]
Looks good 🤩
